DO NOT MERGE - Update for Gradle
WASdev/sample.Spring pull request #6
Opened 2017-10-10 20:34 UTC by dblitza

update for gradle

2017-10-10 20:45 UTC, mattbsox requested changes

2017-10-10 20:45 UTC, mattbsox commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 20:45 UTC, mattbsox commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 20:45 UTC, mattbsox commented on build.gradle
> +        classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:1.1-SNAPSHOT'
update to 2.0-SNAPSHOT

2017-10-10 20:45 UTC, mattbsox commented on build.gradle
> +        configFile = file('src/main/liberty/config/server.xml')
Don't need this if it is the default value `src/main/liberty/config/server.xml`

2017-10-10 20:45 UTC, mattbsox commented on build.gradle
> +        looseApplication = true
LooseApplication is set to true by default. Might want to leave this in for transparency.

2017-10-10 20:45 UTC, mattbsox commented on build.gradle
> +clean.dependsOn 'libertyStop'
remove all of these except for `libertyStart.finalizedBy 'printMessageAboutRunningServer'`

2017-10-10 20:45 UTC, mattbsox commented on build.gradle
> +sourceCompatibility = 1.7
Update these 2 compatibility properties to 1.8

2017-10-11 19:21 UTC, cthigh approved these changes

2017-10-17 04:51 UTC, cthigh approved these changes
Looks good

2017-10-17 22:09 UTC, merged